### PR TITLE
Initial Tweaks

### PR DESCRIPTION
**Pull request by dshanske**
This starts to create a new structure for this plugin. Would like someone to review before I proceed to add more defined logic.

### CODE REVIEW

**Comment by miklb** [comment]
@dshanske I'm still convinced should be adding `u-photo` to the attachment. How are you determining that the photo is the primary content there?

**Comment by dshanske** [comment]
If the post format is image, which is the equivalent of a photo kind.

**Comment by miklb** [comment]
> If the post format is image, which is the equivalent of a photo kind.

I totally missed that. Makes complete sense.

**Comment by dshanske** [comment]
I am going to be doing more. For now, the advantages of this design is that the pieces can be called individually if a theme wants to declare support and require the plugin

**Pull request merged**
